package com.example.toysocialnetwork.Repository;

public class RepoException extends RuntimeException{
    private String msg;

    /**
     *
     * @param message The errorMessage associated with the specific exception
     */
    public RepoException(String message){
        this.msg = message;
    }

    /**
     *
     * @return The errorMessage generated by the exception
     */
    public String getErrorMessage(){
        return msg;
    }
}
